# Generated by Django 4.1 on 2022-08-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeBoard',
            fields=[
                ('bnum', models.AutoField(primary_key=True, serialize=False)),
                ('mid', models.CharField(blank=True, max_length=100)),
                ('btitle', models.CharField(blank=True, max_length=255)),
                ('bcont', models.TextField(blank=True)),
                ('bimg', models.CharField(blank=True, max_length=255)),
                ('bingredient', models.TextField(blank=True)),
                ('bhit', models.IntegerField()),
                ('bcate', models.CharField(blank=True, max_length=100)),
                ('bdate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
