# Generated by Django 4.1 on 2022-08-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedData',
            fields=[
                ('sidx', models.AutoField(primary_key=True, serialize=False)),
                ('snouns', models.CharField(blank=True, max_length=100)),
                ('sdate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
