# Generated by Django 4.1 on 2022-08-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searcheddata',
            name='sType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
